export enum KeyId {
  D0 = 'D0',
  D1 = 'D1',
  D2 = 'D2',
  D3 = 'D3',
  D4 = 'D4',
  D5 = 'D5',
  D6 = 'D6',
  D7 = 'D7',
  D8 = 'D8',
  D9 = 'D9',
  DECIMAL = 'DECIMAL',
  SIGN = 'SIGN',
  PLUS = 'PLUS',
  MINUS = 'MINUS',
  MULTIPLY = 'MULTIPLY',
  DIVIDE = 'DIVIDE',
  EQUALS = 'EQUALS',
  N = 'N',
  I_Y = 'I_Y',
  PV = 'PV',
  PMT = 'PMT',
  FV = 'FV',
  CPT = 'CPT',
  SECOND = 'SECOND',
  ENTER = 'ENTER',
  ARROW_UP = 'ARROW_UP',
  ARROW_DOWN = 'ARROW_DOWN',
  CE_C = 'CE_C',
  ON_OFF = 'ON_OFF',
  STO = 'STO',
  RCL = 'RCL',
  POWER = 'POWER',
  SQRT = 'SQRT',
  LPAREN = 'LPAREN',
  RPAREN = 'RPAREN',
}
export const KEY_IDS = Object.values(KeyId);
export type KeyMetadata = { key: KeyId; label: string; binding: string };
export const KEY_METADATA: KeyMetadata[] = [
  { key: KeyId.D0, label: 'D0', binding: '0' },
  { key: KeyId.D1, label: 'D1', binding: '1' },
  { key: KeyId.D2, label: 'D2', binding: '2' },
  { key: KeyId.D3, label: 'D3', binding: '3' },
  { key: KeyId.D4, label: 'D4', binding: '4' },
  { key: KeyId.D5, label: 'D5', binding: '5' },
  { key: KeyId.D6, label: 'D6', binding: '6' },
  { key: KeyId.D7, label: 'D7', binding: '7' },
  { key: KeyId.D8, label: 'D8', binding: '8' },
  { key: KeyId.D9, label: 'D9', binding: '9' },
  { key: KeyId.DECIMAL, label: 'DECIMAL', binding: 'decimal' },
  { key: KeyId.SIGN, label: 'SIGN', binding: 'sign' },
  { key: KeyId.PLUS, label: 'PLUS', binding: 'plus' },
  { key: KeyId.MINUS, label: 'MINUS', binding: 'minus' },
  { key: KeyId.MULTIPLY, label: 'MULTIPLY', binding: 'multiply' },
  { key: KeyId.DIVIDE, label: 'DIVIDE', binding: 'divide' },
  { key: KeyId.EQUALS, label: 'EQUALS', binding: 'equals' },
  { key: KeyId.N, label: 'N', binding: 'n' },
  { key: KeyId.I_Y, label: 'I/Y', binding: 'i_y' },
  { key: KeyId.PV, label: 'PV', binding: 'pv' },
  { key: KeyId.PMT, label: 'PMT', binding: 'pmt' },
  { key: KeyId.FV, label: 'FV', binding: 'fv' },
  { key: KeyId.CPT, label: 'CPT', binding: 'cpt' },
  { key: KeyId.SECOND, label: 'SECOND', binding: 'second' },
  { key: KeyId.ENTER, label: 'ENTER', binding: 'enter' },
  { key: KeyId.ARROW_UP, label: 'ARROW/UP', binding: 'arrow_up' },
  { key: KeyId.ARROW_DOWN, label: 'ARROW/DOWN', binding: 'arrow_down' },
  { key: KeyId.CE_C, label: 'CE/C', binding: 'ce_c' },
  { key: KeyId.ON_OFF, label: 'ON/OFF', binding: 'on_off' },
  { key: KeyId.STO, label: 'STO', binding: 'sto' },
  { key: KeyId.RCL, label: 'RCL', binding: 'rcl' },
  { key: KeyId.POWER, label: 'POWER', binding: 'power' },
  { key: KeyId.SQRT, label: 'SQRT', binding: 'sqrt' },
  { key: KeyId.LPAREN, label: 'LPAREN', binding: 'lparen' },
  { key: KeyId.RPAREN, label: 'RPAREN', binding: 'rparen' }
];
export const KEYBOARD_BINDINGS: Record<string, KeyId> = {
  '0': KeyId.D0, '1': KeyId.D1, '2': KeyId.D2, '3': KeyId.D3, '4': KeyId.D4,
  '5': KeyId.D5, '6': KeyId.D6, '7': KeyId.D7, '8': KeyId.D8, '9': KeyId.D9,
  '.': KeyId.DECIMAL, '+': KeyId.PLUS, '-': KeyId.MINUS, '*': KeyId.MULTIPLY,
  '/': KeyId.DIVIDE, '=': KeyId.EQUALS, Enter: KeyId.EQUALS, Escape: KeyId.CE_C,
  Backspace: KeyId.CE_C, n: KeyId.N, i: KeyId.I_Y, v: KeyId.PV, m: KeyId.PMT,
  f: KeyId.FV, c: KeyId.CPT, s: KeyId.SECOND, o: KeyId.STO, r: KeyId.RCL,
  ArrowUp: KeyId.ARROW_UP, ArrowDown: KeyId.ARROW_DOWN, '?': KeyId.SECOND
};
