import { KeyId } from './key-id';
export enum SecondaryFunction {
  CF = 'CF',
  NPV = 'NPV',
  IRR = 'IRR',
  BOND = 'BOND',
  DEPR = 'DEPR',
  DATE = 'DATE',
  ICONV = 'ICONV',
  PROFIT = 'PROFIT',
  STAT = 'STAT',
  AMORT = 'AMORT',
  BGN = 'BGN',
  FORMAT = 'FORMAT',
  SET = 'SET',
  CLR_WORK = 'CLR_WORK',
  RESET = 'RESET',
  MEM = 'MEM',
  RECIPROCAL = 'RECIPROCAL',
  PERCENT = 'PERCENT',
  LN = 'LN',
  EXP = 'EXP',
  LOG = 'LOG',
  TEN_X = 'TEN_X',
  FACTORIAL = 'FACTORIAL',
  SQUARE = 'SQUARE',
  MIRR = 'MIRR',
  NFV = 'NFV',
  PB = 'PB',
  DPB = 'DPB',
}
export const SECONDARY_FUNCTION_MAP: Record<KeyId, SecondaryFunction | null> = {
  [KeyId.D0]: null,
  [KeyId.D1]: null,
  [KeyId.D2]: SecondaryFunction.CF,
  [KeyId.D3]: SecondaryFunction.NPV,
  [KeyId.D4]: SecondaryFunction.IRR,
  [KeyId.D5]: SecondaryFunction.BOND,
  [KeyId.D6]: SecondaryFunction.DEPR,
  [KeyId.D7]: SecondaryFunction.DATE,
  [KeyId.D8]: SecondaryFunction.ICONV,
  [KeyId.D9]: SecondaryFunction.STAT,
  [KeyId.DECIMAL]: SecondaryFunction.FORMAT,
  [KeyId.SIGN]: null,
  [KeyId.PLUS]: SecondaryFunction.LOG,
  [KeyId.MINUS]: SecondaryFunction.TEN_X,
  [KeyId.MULTIPLY]: SecondaryFunction.LN,
  [KeyId.DIVIDE]: SecondaryFunction.EXP,
  [KeyId.EQUALS]: SecondaryFunction.FACTORIAL,
  [KeyId.N]: null,
  [KeyId.I_Y]: null,
  [KeyId.PV]: SecondaryFunction.MIRR,
  [KeyId.PMT]: SecondaryFunction.AMORT,
  [KeyId.FV]: SecondaryFunction.NFV,
  [KeyId.CPT]: null,
  [KeyId.SECOND]: null,
  [KeyId.ENTER]: SecondaryFunction.SET,
  [KeyId.ARROW_UP]: SecondaryFunction.BGN,
  [KeyId.ARROW_DOWN]: null,
  [KeyId.CE_C]: SecondaryFunction.CLR_WORK,
  [KeyId.ON_OFF]: SecondaryFunction.RESET,
  [KeyId.STO]: null,
  [KeyId.RCL]: SecondaryFunction.MEM,
  [KeyId.POWER]: SecondaryFunction.RECIPROCAL,
  [KeyId.SQRT]: SecondaryFunction.SQUARE,
  [KeyId.LPAREN]: SecondaryFunction.PB,
  [KeyId.RPAREN]: SecondaryFunction.DPB,
};
export const resolveSecondaryFunction = (key: KeyId): SecondaryFunction | null => SECONDARY_FUNCTION_MAP[key];
